version: "3.8"

services:
  mongodb:
    container_name: purplenotes_db
    image: "mongo"
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_DATABASE: "${MONGO_DB}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
